# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ftrtest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ftrtest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_393fbdb9767b479da08a4878cef36315 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3cc80daf8e3f4e33a7bf7c33b1ca1443 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        context: dotnet
        tags: ftrtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7952d75685264c64bf830e10954dbd0d }}/webimage:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ftrtest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc01f7205c8b414294fcfee0cfe549ae }}
        images: 'ftrtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_393fbdb9767b479da08a4878cef36315 }}/webimage:${{ github.sha }}'
